import { useCallback, useEffect, useRef, useState } from 'react'
import { Arrow } from '../components/Arrow'
import { Mascot } from '../components/Mascot'
import type { ActiveGameProps } from './GameShell'

type Pos = { x: number; y: number }; type Car = { lane: number; x: number; speed: number; dir: number; color: string }
const lanes = [1,2,3,4,5,6,7]
function carsFor(seed: number): Car[] { return lanes.flatMap((lane, index) => [0,1].map(offset => ({ lane, x: ((offset * 3 + index + seed % 3) % 6) - .5, speed: .017 + (index % 3) * .004, dir: index % 2 ? 1 : -1, color: index % 2 ? '#ffdc50' : '#ff6e6e' }))) }
export function CrossGame({ seed, onFinish, setHud, paused }: ActiveGameProps) {
  const game = useRef({ player: { x: 2, y: 8 }, ai: { x: 3, y: 8 }, cars: carsFor(seed), done: false, inputs: [] as string[], aiTicks: 0, betrayal: false }); const [view, setView] = useState(game.current)
  useEffect(() => { game.current = { player: { x: 2, y: 8 }, ai: { x: 3, y: 8 }, cars: carsFor(seed), done: false, inputs: [], aiTicks: 0, betrayal: false }; setView({ ...game.current, cars: [...game.current.cars] }) }, [seed])
  const step = useCallback((key: string) => { const current = game.current; if (paused || current.done) return; const deltas: Record<string, Pos> = { ArrowUp: {x: 0, y: -1}, w: {x: 0, y: -1}, ArrowDown: {x: 0, y: 1}, s: {x: 0, y: 1}, ArrowLeft: {x: -1, y: 0}, a: {x: -1, y: 0}, ArrowRight: {x: 1, y: 0}, d: {x: 1, y: 0} }; const delta = deltas[key]; if (!delta) return; let target = { x: Math.max(0, Math.min(4, current.player.x + delta.x)), y: Math.max(0, Math.min(8, current.player.y + delta.y)) }; current.inputs.push(key); if (!current.betrayal && target.y === 3 && target.x === 2) { current.betrayal = true; target = { x: 2, y: 4 }; current.inputs.push('nowin:centre-roadblock') } current.player = target; if (target.y === 0) { current.done = true; onFinish({ result: 'won', score: 9 - target.y, detail: 'You crossed before NOWIN could.', inputs: current.inputs, betrayalSeen: current.betrayal }); return }; setView({ ...current, player: {...target}, cars: [...current.cars] }) }, [onFinish, paused])
  useEffect(() => { const key = (event: KeyboardEvent) => step(event.key); window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [step])
  useEffect(() => { const timer = window.setInterval(() => { const current = game.current; if (paused || current.done) return; current.cars.forEach(car => { car.x += car.speed * car.dir; if (car.x > 5.4) car.x = -.6; if (car.x < -.6) car.x = 5.4 }); current.aiTicks++; if (current.aiTicks % 9 === 0 && current.ai.y > 0) { current.ai.y--; current.ai.x = current.player.x === current.ai.x ? (current.ai.x + 1) % 5 : current.ai.x; if (current.ai.y === 0) { current.done = true; onFinish({ result: 'lost', score: 8 - current.player.y, detail: 'NOWIN took the finish. Rude.', inputs: current.inputs, betrayalSeen: current.betrayal }); return } } if (current.player.y >= 1 && current.player.y <= 7 && current.cars.some(car => car.lane === current.player.y && Math.abs(car.x - current.player.x) < .52)) { current.done = true; onFinish({ result: 'lost', score: 8 - current.player.y, detail: 'Traffic did not consent.', inputs: current.inputs, betrayalSeen: current.betrayal }); return } if (current.player.y === 3) current.betrayal = true; setView({ ...current, player: {...current.player}, ai: {...current.ai}, cars: [...current.cars] }) }, 55); return () => window.clearInterval(timer) }, [onFinish, paused])
  useEffect(() => setHud(`ROW ${8 - view.player.y}/8 · AI ${8 - view.ai.y}/8`), [setHud, view.ai.y, view.player.y])
  return <div className="cross-game"><div className="cross-race"><span>PLAYER <b>●</b></span><strong>VS</strong><span><b>●</b> NOWIN AI</span></div><p className="game-tip">Cross fast. The centre roadblock at row 3 is a tell: side-step before the AI closes it.</p><div className="cross-board" role="application" aria-label="Crossing game">{Array.from({length: 9}, (_, row) => <div className={`cross-row ${row === 0 ? 'cross-row--finish' : row === 8 ? 'cross-row--start' : ''}`} key={row}>{[0,1,2,3,4].map(col => <i key={col} className="cross-tile"/>)}</div>)}{view.cars.map((car, index) => <b key={index} className="cross-car" style={{ left: `${car.x * 20}%`, top: `${car.lane * (100/9)}%`, background: car.color }} />)}<b className="cross-player" style={{ left: `${view.player.x * 20 + 5}%`, top: `${view.player.y * (100/9) + 2}%` }}>P</b><div className="cross-ai-avatar" style={{ left: `${view.ai.x * 20 + 5}%`, top: `${view.ai.y * (100/9) + 2}%` }} aria-label="NOWIN AI runner"><Mascot mood="taunt"/></div></div><div className="d-pad cross-pad" aria-label="Cross touch controls"><button onClick={() => step('ArrowUp')} aria-label="Move up"><Arrow direction="up"/></button><button onClick={() => step('ArrowLeft')} aria-label="Move left"><Arrow direction="left"/></button><button onClick={() => step('ArrowDown')} aria-label="Move down"><Arrow direction="down"/></button><button onClick={() => step('ArrowRight')} aria-label="Move right"><Arrow /></button></div></div>
}
