import { useCallback, useEffect, useRef, useState } from 'react'
import { SeededRng } from '../game-core/rng'
import type { ActiveGameProps } from './GameShell'

type Board = number[][]
const empty = (): Board => Array.from({ length: 4 }, () => [0, 0, 0, 0])
const clone = (board: Board) => board.map(row => [...row])
function available(board: Board) { const cells: [number, number][] = []; board.forEach((row, y) => row.forEach((tile, x) => { if (!tile) cells.push([x, y]) })); return cells }
function spawn(board: Board, rng: SeededRng) { const cells = available(board); if (cells.length) { const [x, y] = cells[rng.int(cells.length)]; board[y][x] = rng.next() < .9 ? 2 : 4 } }
function lineMove(line: number[]) { const numbers = line.filter(Boolean); const result: number[] = []; let gained = 0; for (let index = 0; index < numbers.length; index++) { if (numbers[index] === numbers[index + 1]) { const value = numbers[index] * 2; result.push(value); gained += value; index++ } else result.push(numbers[index]) } while (result.length < 4) result.push(0); return { line: result, gained } }
function moveBoard(board: Board, direction: string) { const next = empty(); let gained = 0; for (let axis = 0; axis < 4; axis++) { let line = direction === 'left' || direction === 'right' ? board[axis] : board.map(row => row[axis]); if (direction === 'right' || direction === 'down') line = [...line].reverse(); const moved = lineMove(line); gained += moved.gained; if (direction === 'right' || direction === 'down') moved.line.reverse(); for (let index = 0; index < 4; index++) { if (direction === 'left' || direction === 'right') next[axis][index] = moved.line[index]; else next[index][axis] = moved.line[index] } } return { board: next, gained, moved: JSON.stringify(next) !== JSON.stringify(board) } }
function canMove(board: Board) { return available(board).length > 0 || ['left', 'right', 'up', 'down'].some(direction => moveBoard(board, direction).moved) }
function seededBoard(seed: number) { const board = empty(); const rng = new SeededRng(seed); spawn(board, rng); spawn(board, rng); return { board, rng } }
export function MergeGame({ seed, onFinish, setHud, paused }: ActiveGameProps) {
  const initial = seededBoard(seed); const core = useRef({ board: initial.board, rng: initial.rng, score: 0, moves: [] as string[], done: false }); const [view, setView] = useState(core.current); const [warning, setWarning] = useState(false)
  useEffect(() => { const next = seededBoard(seed); core.current = { board: next.board, rng: next.rng, score: 0, moves: [], done: false }; setWarning(false); setView({ ...core.current, board: clone(next.board) }) }, [seed])
  const move = useCallback((direction: string) => { const game = core.current; if (paused || game.done) return; const moved = moveBoard(game.board, direction); if (!moved.moved) return; game.moves.push(direction); game.board = moved.board; game.score += moved.gained; spawn(game.board, game.rng); const peak = Math.max(...game.board.flat()); if (peak >= 64) setWarning(true); if (peak >= 128) { game.done = true; onFinish({ result: 'won', score: game.score, detail: '128. NOWIN is typing...', inputs: game.moves, betrayalSeen: warning }); return } if (!canMove(game.board)) { game.done = true; onFinish({ result: 'lost', score: game.score, detail: 'No legal merges left.', inputs: game.moves, betrayalSeen: warning }); return } setView({ ...game, board: clone(game.board) }) }, [onFinish, paused, warning])
  useEffect(() => { const map: Record<string, string> = { ArrowLeft: 'left', a: 'left', ArrowRight: 'right', d: 'right', ArrowUp: 'up', w: 'up', ArrowDown: 'down', s: 'down' }; const key = (event: KeyboardEvent) => { if (map[event.key]) { event.preventDefault(); move(map[event.key]) } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [move])
  useEffect(() => setHud(`${view.score.toLocaleString()} PTS · ${Math.max(...view.board.flat())}`), [setHud, view.board, view.score])
  const cells = view.board.flatMap((row, y) => row.map((value, x) => ({ value, x, y })))
  return <div className="merge-game"><p className="game-tip">Merge to 128. At 64, the corner glows: don&apos;t maroon your biggest tile there.</p><div className={`merge-board ${warning ? 'merge-board--warning' : ''}`} role="application" aria-label="2048 game">{cells.map(cell => <button onClick={() => {}} key={`${cell.x}-${cell.y}`} className={`merge-cell merge-cell--${cell.value}`} aria-label={cell.value ? `${cell.value} tile` : 'empty tile'}>{cell.value || ''}</button>)}</div><div className="move-pad"><button onClick={() => move('up')}>↑</button><div><button onClick={() => move('left')}>←</button><button onClick={() => move('down')}>↓</button><button onClick={() => move('right')}>→</button></div></div></div>
}
