import { useEffect, useState } from 'react'
import type { ActiveGameProps } from './GameShell'

const SIZE = 9
const baseMines = [[1,1],[4,1],[7,1],[2,3],[6,3],[1,5],[4,5],[7,5],[2,7],[6,7]]
type Cell = { mine: boolean; open: boolean; flag: boolean; count: number }
function createBoard(seed: number): Cell[][] { const shift = Math.abs(seed) % 2; const mines = baseMines.map(([x, y]) => [shift ? 8 - x : x, y]); return Array.from({ length: SIZE }, (_, y) => Array.from({ length: SIZE }, (_, x) => { const mine = mines.some(([mx, my]) => mx === x && my === y); const count = Array.from({ length: 9 }, (_, index) => { const dx = index % 3 - 1; const dy = Math.floor(index / 3) - 1; return mines.some(([mx, my]) => mx === x + dx && my === y + dy) ? 1 : 0 }).reduce<number>((a,b) => a+b, 0); return { mine, open: false, flag: false, count } })) }
export function MinesGame({ seed, onFinish, setHud, paused }: ActiveGameProps) {
  const [board, setBoard] = useState(() => createBoard(seed)); const [flagMode, setFlagMode] = useState(false); const [done, setDone] = useState(false); const [moves, setMoves] = useState<string[]>([])
  useEffect(() => { setBoard(createBoard(seed)); setFlagMode(false); setDone(false); setMoves([]) }, [seed])
  const revealed = board.flat().filter(cell => cell.open && !cell.mine).length; const flags = board.flat().filter(cell => cell.flag).length
  useEffect(() => setHud(`${revealed}/${SIZE * SIZE - baseMines.length} CLEAR · ${flags} FLAGS`), [flags, revealed, setHud])
  const reveal = (x: number, y: number) => { if (paused || done) return; const cell = board[y][x]; if (cell.flag || cell.open) return; const next = board.map(row => row.map(item => ({ ...item }))); const open = (ox: number, oy: number) => { if (ox < 0 || oy < 0 || ox >= SIZE || oy >= SIZE) return; const at = next[oy][ox]; if (at.open || at.flag) return; at.open = true; if (!at.mine && at.count === 0) for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) if (dx || dy) open(ox + dx, oy + dy) }; open(x,y); const log = [...moves, `reveal:${x},${y}`]; setMoves(log); setBoard(next); if (cell.mine) { setDone(true); onFinish({ result: 'lost', score: revealed, detail: 'That symmetry had teeth.', inputs: log, betrayalSeen: revealed > 30 }); return } const safelyOpen = next.flat().filter(item => item.open && !item.mine).length; if (safelyOpen === SIZE * SIZE - baseMines.length) { setDone(true); onFinish({ result: 'won', score: safelyOpen, detail: 'Every clue, every square.', inputs: log, betrayalSeen: true }) } }
  const flag = (x: number, y: number) => { if (paused || done || board[y][x].open) return; const next = board.map(row => row.map(item => ({ ...item }))); next[y][x].flag = !next[y][x].flag; setMoves(previous => [...previous, `flag:${x},${y}`]); setBoard(next) }
  return <div className="mines-game"><div className="mines-top"><p className="game-tip">The mirror is bait. Count both clues before you flag the centre.</p><button className={`mode-button ${flagMode ? 'mode-button--on' : ''}`} onClick={() => setFlagMode(value => !value)}>⚑ {flagMode ? 'FLAG MODE' : 'REVEAL MODE'}</button></div><div className="mines-board" role="application" aria-label="Mines game">{board.flatMap((row, y) => row.map((cell, x) => <button key={`${x}-${y}`} className={`mine-cell ${cell.open ? 'mine-cell--open' : ''} ${cell.flag ? 'mine-cell--flag' : ''} ${cell.open && cell.mine ? 'mine-cell--boom' : ''}`} onClick={() => flagMode ? flag(x, y) : reveal(x, y)} onContextMenu={event => { event.preventDefault(); flag(x,y) }} aria-label={`row ${y + 1}, column ${x + 1}`}>{cell.open ? cell.mine ? '✹' : cell.count || '' : cell.flag ? '⚑' : ''}</button>))}</div></div>
}
