import { useEffect, useRef, useState } from 'react'
import type { ActiveGameProps } from './GameShell'
const W = 800; const H = 440
export function PongGame({ seed: _seed, onFinish, setHud, paused }: ActiveGameProps) {
  const game = useRef({ player: 220, ai: 220, ball: { x: 400, y: 220, vx: -4.2, vy: 2.1 }, p: 0, a: 0, done: false, key: 0, inputs: [] as string[], warned: false }); const [view, setView] = useState(game.current); const last = useRef(0)
  useEffect(() => { const drift = _seed % 2 ? 1 : -1; game.current = { player: 220, ai: 220, ball: { x: 400, y: 220, vx: -4.2 * drift, vy: 2.1 }, p: 0, a: 0, done: false, key: 0, inputs: [], warned: false }; setView({ ...game.current, ball: {...game.current.ball} }) }, [_seed])
  useEffect(() => { const down = (event: KeyboardEvent) => { if (event.key === 'w' || event.key === 'ArrowUp') game.current.key = -1; if (event.key === 's' || event.key === 'ArrowDown') game.current.key = 1 }; const up = () => game.current.key = 0; window.addEventListener('keydown', down); window.addEventListener('keyup', up); return () => { window.removeEventListener('keydown', down); window.removeEventListener('keyup', up) } }, [])
  const movePointer = (event: React.PointerEvent<SVGSVGElement>) => { const box = event.currentTarget.getBoundingClientRect(); game.current.player = Math.max(42, Math.min(H - 42, ((event.clientY - box.top) / box.height) * H)); game.current.inputs.push(`pointer:${Math.round(game.current.player)}`) }
  useEffect(() => { let frame = 0; const reset = (towardsPlayer: boolean) => { const current = game.current; const flip = ((_seed + current.p * 3 + current.a * 5) % 2 ? 1 : -1); current.ball = { x: 400, y: 220, vx: towardsPlayer ? -4.2 : 4.2, vy: flip * 2.2 } }
    const tick = (now: number) => { frame = requestAnimationFrame(tick); const current = game.current; if (paused || current.done) return; const dt = Math.min(2, (now - last.current || 16) / 16); last.current = now; current.player = Math.max(42, Math.min(H-42, current.player + current.key * 7 * dt)); const target = current.ball.y + (current.ball.vx > 0 ? current.ball.vy * 14 : 0); current.ai += Math.max(-4.1, Math.min(4.1, target - current.ai)) * .22 * dt; current.ai = Math.max(42, Math.min(H - 42, current.ai)); const ball = current.ball; ball.x += ball.vx * dt; ball.y += ball.vy * dt; if (ball.y < 10 || ball.y > H - 10) { ball.vy *= -1; ball.y = Math.max(10, Math.min(H-10,ball.y)) }
      if (ball.vx < 0 && ball.x < 55 && ball.x > 34 && Math.abs(ball.y - current.player) < 50) { ball.vx = Math.abs(ball.vx) * 1.04; ball.vy += (ball.y - current.player) * .045; current.inputs.push('return') }
      if (ball.vx > 0 && ball.x > W - 55 && ball.x < W - 34 && Math.abs(ball.y - current.ai) < 50) { ball.vx = -Math.abs(ball.vx) * 1.03; ball.vy += (ball.y - current.ai) * .042 }
      if (ball.x < -20) { current.a++; if (current.a === 7) { current.done = true; onFinish({ result: 'lost', score: current.p, detail: 'NOWIN got seven. It is unbearable.', inputs: current.inputs, betrayalSeen: current.warned }); return }; reset(false) }
      if (ball.x > W + 20) { current.p++; if (current.p === 6 || current.a === 6) current.warned = true; if (current.p === 7) { current.done = true; onFinish({ result: 'won', score: current.p, detail: 'Seven points. You actually did it.', inputs: current.inputs, betrayalSeen: current.warned }); return }; reset(true) }
      if (current.warned && (current.p === 6 || current.a === 6)) { ball.vx *= 1.0015 }
      setView({ ...current, ball: {...ball} })
    }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, [onFinish, paused])
  useEffect(() => setHud(`${view.p} — ${view.a}${view.warned ? ' · MATCH POINT PACE!' : ''}`), [setHud, view.a, view.p, view.warned])
  return <div className="pong-game"><div className="pong-score"><b>{view.p}</b><span>YOU / NOWIN</span><b>{view.a}</b></div><p className="game-tip">Move your paddle. At 6, the ball gets a blue tell before the speed shift.</p><svg className="pong-stage" viewBox={`0 0 ${W} ${H}`} onPointerMove={movePointer} role="application" aria-label="Pong game"><rect width={W} height={H} rx="18" fill="#152f4e"/><path d={`M400 0v${H}`} stroke="#69e9df" strokeDasharray="12 14" strokeWidth="4" opacity=".5"/><rect x="36" y={view.player - 42} width="15" height="84" rx="8" fill="#ffe55a"/><rect x={W-51} y={view.ai - 42} width="15" height="84" rx="8" fill="#ff5aa2"/><circle cx={view.ball.x} cy={view.ball.y} r="11" fill={view.warned ? '#69e9df' : '#fff8e6'} stroke="#17182b" strokeWidth="4"/></svg><div className="pong-controls"><button onPointerDown={() => game.current.key = -1} onPointerUp={() => game.current.key = 0}>UP</button><button onPointerDown={() => game.current.key = 1} onPointerUp={() => game.current.key = 0}>DOWN</button></div></div>
}
